const phoneList = [
  {
    _id: "1",
    userName: "Smit",
    company: "Samsung",
    model: "Galaxy A-30s",
    price: "22000 Rs.",
    battery: "4000 mAh",
    ram: "4 GB",
    rom: "128 GB",
    cameraRating: "4",
    rating: "4.5",
    review: "",
  },
  {
    _id: "2",
    userName: "Smit",
    company: "iPhone",
    model: "iPhone 14",
    price: "122000 Rs.",
    battery: "3300 mAh",
    ram: "6 GB",
    rom: "128GB",
    cameraRating: "4.5",
    rating: "4.5",
    review: "I loved it.",
  },
  {
    _id: "3",
    userName: "meet",
    company: "OnePlus",
    model: "Nord CE 3",
    price: "20000 Rs.",
    battery: "5000 mAh",
    ram: "8 GB",
    rom: "128GB",
    cameraRating: "4.2",
    rating: "4",
    review:
      "This phone comes with a 80 Watt. Takes less than an hour for 0 to 100 percent.",
  },
  {
    _id: "4",
    userName: "Raj",
    company: "OnePlus",
    model: "CE 3",
    price: "16000 Rs.",
    battery: "4000 mAh",
    ram: "6 GB",
    rom: "128GB",
    cameraRating: "4",
    rating: "4.2",
    review: "This phone comes with a 80 Watt.",
  },
];
export default phoneList;
